services:
  - type: web
    name: streamify-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production

  - type: web
    name: streamify-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    envVars:
      - key: NODE_ENV
        value: production